-- USERS
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Angela', 'Hudson', 'user1@example.com', 'pass1', '3622757075', 'CUSTOMER', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Gina', 'Sexton', 'user2@example.com', 'pass2', '6383301819', 'CUSTOMER', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Richard', 'Davis', 'user3@example.com', 'pass3', '2047495168', 'ADMIN', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Tracy', 'Owens', 'user4@example.com', 'pass4', '1273575129', 'ADMIN', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Lindsay', 'Allen', 'user5@example.com', 'pass5', '8519677373', 'CUSTOMER', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Andrew', 'Calhoun', 'user6@example.com', 'pass6', '6195386414', 'ADMIN', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Michael', 'Brown', 'user7@example.com', 'pass7', '6672236221', 'ADMIN', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Erica', 'Wood', 'user8@example.com', 'pass8', '3011817619', 'ADMIN', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Julie', 'Briggs', 'user9@example.com', 'pass9', '0479538768', 'CUSTOMER', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Mary', 'Johns', 'user10@example.com', 'pass10', '1290032499', 'CUSTOMER', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Margaret', 'Callahan', 'user11@example.com', 'pass11', '8703913098', 'CUSTOMER', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Amanda', 'Guerrero', 'user12@example.com', 'pass12', '4103215332', 'CUSTOMER', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Jennifer', 'Hill', 'user13@example.com', 'pass13', '3486057698', 'ADMIN', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Jeffrey', 'Phillips', 'user14@example.com', 'pass14', '0402792325', 'ADMIN', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Sarah', 'Murray', 'user15@example.com', 'pass15', '2255507501', 'ADMIN', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Paul', 'Carter', 'user16@example.com', 'pass16', '6562141921', 'ADMIN', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Crystal', 'Weaver', 'user17@example.com', 'pass17', '5519457967', 'CUSTOMER', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Kelly', 'Houston', 'user18@example.com', 'pass18', '3361604238', 'ADMIN', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Amy', 'Sanchez', 'user19@example.com', 'pass19', '4631661991', 'CUSTOMER', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('David', 'Anderson', 'user20@example.com', 'pass20', '8808525361', 'ADMIN', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Cindy', 'Dixon', 'user21@example.com', 'pass21', '6853174092', 'CUSTOMER', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Justin', 'Lee', 'user22@example.com', 'pass22', '1696272658', 'CUSTOMER', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Alexis', 'Bowman', 'user23@example.com', 'pass23', '8235050537', 'ADMIN', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Mikayla', 'Frazier', 'user24@example.com', 'pass24', '7245758220', 'ADMIN', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Claudia', 'White', 'user25@example.com', 'pass25', '0011352626', 'CUSTOMER', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Christopher', 'Phillips', 'user26@example.com', 'pass26', '6583220748', 'CUSTOMER', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Lisa', 'Wilson', 'user27@example.com', 'pass27', '3332114148', 'CUSTOMER', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Michelle', 'Simpson', 'user28@example.com', 'pass28', '3595516347', 'CUSTOMER', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Elijah', 'Martinez', 'user29@example.com', 'pass29', '8001571984', 'ADMIN', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Nicole', 'Schmidt', 'user30@example.com', 'pass30', '8746138909', 'CUSTOMER', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Kathryn', 'Bryant', 'user31@example.com', 'pass31', '2195537396', 'ADMIN', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Paul', 'Higgins', 'user32@example.com', 'pass32', '5764988028', 'ADMIN', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Carlos', 'Ortiz', 'user33@example.com', 'pass33', '7844895761', 'CUSTOMER', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Cynthia', 'Hill', 'user34@example.com', 'pass34', '0479870183', 'CUSTOMER', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Gary', 'Kennedy', 'user35@example.com', 'pass35', '5167137755', 'CUSTOMER', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Cody', 'Mitchell', 'user36@example.com', 'pass36', '1029420555', 'CUSTOMER', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Matthew', 'Hale', 'user37@example.com', 'pass37', '7743234549', 'CUSTOMER', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Craig', 'Foster', 'user38@example.com', 'pass38', '2608379275', 'ADMIN', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Alex', 'Lamb', 'user39@example.com', 'pass39', '7413110128', 'ADMIN', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Amanda', 'Cooper', 'user40@example.com', 'pass40', '6204025647', 'CUSTOMER', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Mark', 'Valencia', 'user41@example.com', 'pass41', '4914491818', 'CUSTOMER', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Ryan', 'Chandler', 'user42@example.com', 'pass42', '9819625522', 'CUSTOMER', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Thomas', 'Kelly', 'user43@example.com', 'pass43', '9769192013', 'CUSTOMER', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Ashley', 'Williams', 'user44@example.com', 'pass44', '2393820482', 'ADMIN', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Leslie', 'Deleon', 'user45@example.com', 'pass45', '5303561422', 'CUSTOMER', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Pamela', 'Patel', 'user46@example.com', 'pass46', '6103457406', 'CUSTOMER', TRUE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Tanya', 'Hill', 'user47@example.com', 'pass47', '2965429756', 'CUSTOMER', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Tyler', 'Wood', 'user48@example.com', 'pass48', '4992028176', 'ADMIN', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Samantha', 'Luna', 'user49@example.com', 'pass49', '3772390835', 'CUSTOMER', FALSE);
INSERT INTO users (first_name, last_name, email, password, phone_number, role, is_active) VALUES ('Mark', 'Young', 'user50@example.com', 'pass50', '6945649089', 'CUSTOMER', TRUE);


-- ROOMS
INSERT INTO rooms (room_number, room_type, price_per_night, capacity, description) VALUES (101, 'SINGLE', 369.49, 2, 'Pick party environmental according though body.');
INSERT INTO rooms (room_number, room_type, price_per_night, capacity, description) VALUES (102, 'SUITE', 139.86, 5, 'Imagine score old office long dinner make.');
INSERT INTO rooms (room_number, room_type, price_per_night, capacity, description) VALUES (103, 'SUITE', 101.19, 3, 'Service do particularly organization fall rock.');
INSERT INTO rooms (room_number, room_type, price_per_night, capacity, description) VALUES (104, 'DOUBLE', 149.03, 5, 'Life head interest because strong teacher appear.');
INSERT INTO rooms (room_number, room_type, price_per_night, capacity, description) VALUES (105, 'SINGLE', 345.82, 2, 'Between off generation.');
INSERT INTO rooms (room_number, room_type, price_per_night, capacity, description) VALUES (106, 'DOUBLE', 114.77, 4, 'Early sister later rise through.');
INSERT INTO rooms (room_number, room_type, price_per_night, capacity, description) VALUES (107, 'DOUBLE', 76.55, 5, 'Special century miss government.');
INSERT INTO rooms (room_number, room_type, price_per_night, capacity, description) VALUES (108, 'SUITE', 306.58, 5, 'Number throw foreign less.');
INSERT INTO rooms (room_number, room_type, price_per_night, capacity, description) VALUES (109, 'DOUBLE', 116.69, 2, 'Establish fast image beat.');
INSERT INTO rooms (room_number, room_type, price_per_night, capacity, description) VALUES (110, 'DOUBLE', 143.21, 1, 'Ahead nation choose say see break child field.');


-- BOOKING REFERENCES
INSERT INTO booking_references (reference_code) VALUES ('BR-1001');
INSERT INTO booking_references (reference_code) VALUES ('BR-1002');
INSERT INTO booking_references (reference_code) VALUES ('BR-1003');
INSERT INTO booking_references (reference_code) VALUES ('BR-1004');
INSERT INTO booking_references (reference_code) VALUES ('BR-1005');
INSERT INTO booking_references (reference_code) VALUES ('BR-1006');
INSERT INTO booking_references (reference_code) VALUES ('BR-1007');
INSERT INTO booking_references (reference_code) VALUES ('BR-1008');
INSERT INTO booking_references (reference_code) VALUES ('BR-1009');
INSERT INTO booking_references (reference_code) VALUES ('BR-1010');
INSERT INTO booking_references (reference_code) VALUES ('BR-1011');
INSERT INTO booking_references (reference_code) VALUES ('BR-1012');
INSERT INTO booking_references (reference_code) VALUES ('BR-1013');
INSERT INTO booking_references (reference_code) VALUES ('BR-1014');
INSERT INTO booking_references (reference_code) VALUES ('BR-1015');
INSERT INTO booking_references (reference_code) VALUES ('BR-1016');
INSERT INTO booking_references (reference_code) VALUES ('BR-1017');
INSERT INTO booking_references (reference_code) VALUES ('BR-1018');
INSERT INTO booking_references (reference_code) VALUES ('BR-1019');
INSERT INTO booking_references (reference_code) VALUES ('BR-1020');
INSERT INTO booking_references (reference_code) VALUES ('BR-1021');
INSERT INTO booking_references (reference_code) VALUES ('BR-1022');
INSERT INTO booking_references (reference_code) VALUES ('BR-1023');
INSERT INTO booking_references (reference_code) VALUES ('BR-1024');
INSERT INTO booking_references (reference_code) VALUES ('BR-1025');
INSERT INTO booking_references (reference_code) VALUES ('BR-1026');
INSERT INTO booking_references (reference_code) VALUES ('BR-1027');
INSERT INTO booking_references (reference_code) VALUES ('BR-1028');
INSERT INTO booking_references (reference_code) VALUES ('BR-1029');
INSERT INTO booking_references (reference_code) VALUES ('BR-1030');
INSERT INTO booking_references (reference_code) VALUES ('BR-1031');
INSERT INTO booking_references (reference_code) VALUES ('BR-1032');
INSERT INTO booking_references (reference_code) VALUES ('BR-1033');
INSERT INTO booking_references (reference_code) VALUES ('BR-1034');
INSERT INTO booking_references (reference_code) VALUES ('BR-1035');
INSERT INTO booking_references (reference_code) VALUES ('BR-1036');
INSERT INTO booking_references (reference_code) VALUES ('BR-1037');
INSERT INTO booking_references (reference_code) VALUES ('BR-1038');
INSERT INTO booking_references (reference_code) VALUES ('BR-1039');
INSERT INTO booking_references (reference_code) VALUES ('BR-1040');
INSERT INTO booking_references (reference_code) VALUES ('BR-1041');
INSERT INTO booking_references (reference_code) VALUES ('BR-1042');
INSERT INTO booking_references (reference_code) VALUES ('BR-1043');
INSERT INTO booking_references (reference_code) VALUES ('BR-1044');
INSERT INTO booking_references (reference_code) VALUES ('BR-1045');
INSERT INTO booking_references (reference_code) VALUES ('BR-1046');
INSERT INTO booking_references (reference_code) VALUES ('BR-1047');
INSERT INTO booking_references (reference_code) VALUES ('BR-1048');
INSERT INTO booking_references (reference_code) VALUES ('BR-1049');
INSERT INTO booking_references (reference_code) VALUES ('BR-1050');
INSERT INTO booking_references (reference_code) VALUES ('BR-1051');
INSERT INTO booking_references (reference_code) VALUES ('BR-1052');
INSERT INTO booking_references (reference_code) VALUES ('BR-1053');
INSERT INTO booking_references (reference_code) VALUES ('BR-1054');
INSERT INTO booking_references (reference_code) VALUES ('BR-1055');
INSERT INTO booking_references (reference_code) VALUES ('BR-1056');
INSERT INTO booking_references (reference_code) VALUES ('BR-1057');
INSERT INTO booking_references (reference_code) VALUES ('BR-1058');
INSERT INTO booking_references (reference_code) VALUES ('BR-1059');
INSERT INTO booking_references (reference_code) VALUES ('BR-1060');
INSERT INTO booking_references (reference_code) VALUES ('BR-1061');
INSERT INTO booking_references (reference_code) VALUES ('BR-1062');
INSERT INTO booking_references (reference_code) VALUES ('BR-1063');
INSERT INTO booking_references (reference_code) VALUES ('BR-1064');
INSERT INTO booking_references (reference_code) VALUES ('BR-1065');
INSERT INTO booking_references (reference_code) VALUES ('BR-1066');
INSERT INTO booking_references (reference_code) VALUES ('BR-1067');
INSERT INTO booking_references (reference_code) VALUES ('BR-1068');
INSERT INTO booking_references (reference_code) VALUES ('BR-1069');
INSERT INTO booking_references (reference_code) VALUES ('BR-1070');
INSERT INTO booking_references (reference_code) VALUES ('BR-1071');
INSERT INTO booking_references (reference_code) VALUES ('BR-1072');
INSERT INTO booking_references (reference_code) VALUES ('BR-1073');
INSERT INTO booking_references (reference_code) VALUES ('BR-1074');
INSERT INTO booking_references (reference_code) VALUES ('BR-1075');
INSERT INTO booking_references (reference_code) VALUES ('BR-1076');
INSERT INTO booking_references (reference_code) VALUES ('BR-1077');
INSERT INTO booking_references (reference_code) VALUES ('BR-1078');
INSERT INTO booking_references (reference_code) VALUES ('BR-1079');
INSERT INTO booking_references (reference_code) VALUES ('BR-1080');
INSERT INTO booking_references (reference_code) VALUES ('BR-1081');
INSERT INTO booking_references (reference_code) VALUES ('BR-1082');
INSERT INTO booking_references (reference_code) VALUES ('BR-1083');
INSERT INTO booking_references (reference_code) VALUES ('BR-1084');
INSERT INTO booking_references (reference_code) VALUES ('BR-1085');
INSERT INTO booking_references (reference_code) VALUES ('BR-1086');
INSERT INTO booking_references (reference_code) VALUES ('BR-1087');
INSERT INTO booking_references (reference_code) VALUES ('BR-1088');
INSERT INTO booking_references (reference_code) VALUES ('BR-1089');
INSERT INTO booking_references (reference_code) VALUES ('BR-1090');
INSERT INTO booking_references (reference_code) VALUES ('BR-1091');
INSERT INTO booking_references (reference_code) VALUES ('BR-1092');
INSERT INTO booking_references (reference_code) VALUES ('BR-1093');
INSERT INTO booking_references (reference_code) VALUES ('BR-1094');
INSERT INTO booking_references (reference_code) VALUES ('BR-1095');
INSERT INTO booking_references (reference_code) VALUES ('BR-1096');
INSERT INTO booking_references (reference_code) VALUES ('BR-1097');
INSERT INTO booking_references (reference_code) VALUES ('BR-1098');
INSERT INTO booking_references (reference_code) VALUES ('BR-1099');
INSERT INTO booking_references (reference_code) VALUES ('BR-1100');


-- PAYMENTS
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (644.63, 'TX-1001', 'CASH_ON_DELIVERY', CURRENT_DATE, 'CANCELED', 10);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (869.55, 'TX-1002', 'VISA', CURRENT_DATE, 'FAILED', 41);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (255.22, 'TX-1003', 'MTN_MOBILE_MONEY', CURRENT_DATE, 'CANCELED', 22);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (158.69, 'TX-1004', 'DISCOVER', CURRENT_DATE, 'CANCELED', 26);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (749.33, 'TX-1005', 'DISCOVER', CURRENT_DATE, 'CANCELED', 6);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (434.96, 'TX-1006', 'MTN_MOBILE_MONEY', CURRENT_DATE, 'CONFIRMED', 31);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (384.01, 'TX-1007', 'VISA', CURRENT_DATE, 'DECLINED', 30);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (276.2, 'TX-1008', 'AMERICAN_EXPRESS', CURRENT_DATE, 'CONFIRMED', 10);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (942.79, 'TX-1009', 'MASTER_CARD', CURRENT_DATE, 'FAILED', 9);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (622.82, 'TX-1010', 'STRIPE', CURRENT_DATE, 'CONFIRMED', 7);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (186.51, 'TX-1011', 'STRIPE', CURRENT_DATE, 'CONFIRMED', 25);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (224.42, 'TX-1012', 'DISCOVER', CURRENT_DATE, 'FAILED', 21);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (431.57, 'TX-1013', 'MASTER_CARD', CURRENT_DATE, 'CONFIRMED', 17);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (418.51, 'TX-1014', 'MTN_MOBILE_MONEY', CURRENT_DATE, 'FAILED', 27);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (93.63, 'TX-1015', 'MTN_MOBILE_MONEY', CURRENT_DATE, 'PENDING', 19);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (512.15, 'TX-1016', 'MASTER_CARD', CURRENT_DATE, 'DECLINED', 15);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (810.93, 'TX-1017', 'MTN_MOBILE_MONEY', CURRENT_DATE, 'CONFIRMED', 49);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (92.11, 'TX-1018', 'STRIPE', CURRENT_DATE, 'PENDING', 7);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (331.69, 'TX-1019', 'VISA', CURRENT_DATE, 'DECLINED', 45);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (444.36, 'TX-1020', 'PAYPAL', CURRENT_DATE, 'CONFIRMED', 12);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (511.07, 'TX-1021', 'MTN_MOBILE_MONEY', CURRENT_DATE, 'CANCELED', 17);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (853.82, 'TX-1022', 'CASH_ON_DELIVERY', CURRENT_DATE, 'DECLINED', 26);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (717.39, 'TX-1023', 'MASTER_CARD', CURRENT_DATE, 'CONFIRMED', 25);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (742.17, 'TX-1024', 'PAYPAL', CURRENT_DATE, 'DECLINED', 38);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (916.77, 'TX-1025', 'CASH_ON_DELIVERY', CURRENT_DATE, 'DECLINED', 24);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (332.71, 'TX-1026', 'STRIPE', CURRENT_DATE, 'DECLINED', 31);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (177.62, 'TX-1027', 'VISA', CURRENT_DATE, 'FAILED', 11);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (639.42, 'TX-1028', 'STRIPE', CURRENT_DATE, 'CONFIRMED', 2);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (297.46, 'TX-1029', 'VISA', CURRENT_DATE, 'CANCELED', 45);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (722.34, 'TX-1030', 'MTN_MOBILE_MONEY', CURRENT_DATE, 'FAILED', 22);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (81.17, 'TX-1031', 'VISA', CURRENT_DATE, 'DECLINED', 41);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (110.25, 'TX-1032', 'STRIPE', CURRENT_DATE, 'FAILED', 37);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (113.65, 'TX-1033', 'CASH_ON_DELIVERY', CURRENT_DATE, 'CANCELED', 41);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (206.43, 'TX-1034', 'VISA', CURRENT_DATE, 'PENDING', 1);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (595.76, 'TX-1035', 'CASH_ON_DELIVERY', CURRENT_DATE, 'DECLINED', 4);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (474.5, 'TX-1036', 'DISCOVER', CURRENT_DATE, 'PENDING', 43);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (486.23, 'TX-1037', 'PAYPAL', CURRENT_DATE, 'CANCELED', 5);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (271.85, 'TX-1038', 'PAYPAL', CURRENT_DATE, 'CANCELED', 17);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (731.65, 'TX-1039', 'MASTER_CARD', CURRENT_DATE, 'FAILED', 48);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (591.92, 'TX-1040', 'VISA', CURRENT_DATE, 'FAILED', 46);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (652.42, 'TX-1041', 'MTN_MOBILE_MONEY', CURRENT_DATE, 'CONFIRMED', 4);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (93.15, 'TX-1042', 'PAYPAL', CURRENT_DATE, 'DECLINED', 20);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (959.63, 'TX-1043', 'CASH_ON_DELIVERY', CURRENT_DATE, 'PENDING', 13);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (679.63, 'TX-1044', 'VISA', CURRENT_DATE, 'FAILED', 25);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (419.38, 'TX-1045', 'VISA', CURRENT_DATE, 'PENDING', 43);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (764.83, 'TX-1046', 'PAYPAL', CURRENT_DATE, 'CANCELED', 23);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (682.8, 'TX-1047', 'MTN_MOBILE_MONEY', CURRENT_DATE, 'CANCELED', 3);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (349.38, 'TX-1048', 'DISCOVER', CURRENT_DATE, 'FAILED', 34);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (686.45, 'TX-1049', 'MASTER_CARD', CURRENT_DATE, 'CANCELED', 46);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (336.73, 'TX-1050', 'STRIPE', CURRENT_DATE, 'PENDING', 20);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (661.22, 'TX-1051', 'MASTER_CARD', CURRENT_DATE, 'CONFIRMED', 6);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (615.56, 'TX-1052', 'PAYPAL', CURRENT_DATE, 'DECLINED', 38);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (841.04, 'TX-1053', 'DISCOVER', CURRENT_DATE, 'DECLINED', 45);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (86.08, 'TX-1054', 'VISA', CURRENT_DATE, 'DECLINED', 49);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (637.15, 'TX-1055', 'CASH_ON_DELIVERY', CURRENT_DATE, 'PENDING', 12);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (720.03, 'TX-1056', 'AMERICAN_EXPRESS', CURRENT_DATE, 'DECLINED', 12);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (346.49, 'TX-1057', 'CASH_ON_DELIVERY', CURRENT_DATE, 'PENDING', 28);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (336.3, 'TX-1058', 'VISA', CURRENT_DATE, 'CANCELED', 33);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (97.49, 'TX-1059', 'CASH_ON_DELIVERY', CURRENT_DATE, 'FAILED', 35);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (96.03, 'TX-1060', 'PAYPAL', CURRENT_DATE, 'CONFIRMED', 39);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (107.53, 'TX-1061', 'PAYPAL', CURRENT_DATE, 'CONFIRMED', 29);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (965.53, 'TX-1062', 'STRIPE', CURRENT_DATE, 'PENDING', 34);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (781.04, 'TX-1063', 'STRIPE', CURRENT_DATE, 'FAILED', 30);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (492.47, 'TX-1064', 'VISA', CURRENT_DATE, 'CONFIRMED', 42);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (513.57, 'TX-1065', 'PAYPAL', CURRENT_DATE, 'CANCELED', 12);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (995.1, 'TX-1066', 'VISA', CURRENT_DATE, 'CONFIRMED', 7);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (297.47, 'TX-1067', 'PAYPAL', CURRENT_DATE, 'DECLINED', 49);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (285.72, 'TX-1068', 'PAYPAL', CURRENT_DATE, 'CANCELED', 1);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (193.02, 'TX-1069', 'AMERICAN_EXPRESS', CURRENT_DATE, 'PENDING', 45);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (559.08, 'TX-1070', 'DISCOVER', CURRENT_DATE, 'CONFIRMED', 50);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (897.74, 'TX-1071', 'VISA', CURRENT_DATE, 'PENDING', 26);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (387.37, 'TX-1072', 'DISCOVER', CURRENT_DATE, 'DECLINED', 45);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (719.43, 'TX-1073', 'MTN_MOBILE_MONEY', CURRENT_DATE, 'PENDING', 44);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (722.46, 'TX-1074', 'DISCOVER', CURRENT_DATE, 'FAILED', 28);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (218.35, 'TX-1075', 'VISA', CURRENT_DATE, 'PENDING', 27);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (983.62, 'TX-1076', 'MTN_MOBILE_MONEY', CURRENT_DATE, 'FAILED', 29);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (197.96, 'TX-1077', 'MASTER_CARD', CURRENT_DATE, 'CONFIRMED', 22);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (116.91, 'TX-1078', 'STRIPE', CURRENT_DATE, 'PENDING', 21);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (549.18, 'TX-1079', 'STRIPE', CURRENT_DATE, 'PENDING', 31);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (124.29, 'TX-1080', 'CASH_ON_DELIVERY', CURRENT_DATE, 'DECLINED', 31);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (581.8, 'TX-1081', 'PAYPAL', CURRENT_DATE, 'DECLINED', 9);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (706.88, 'TX-1082', 'MTN_MOBILE_MONEY', CURRENT_DATE, 'CONFIRMED', 9);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (992.96, 'TX-1083', 'PAYPAL', CURRENT_DATE, 'CANCELED', 49);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (499.43, 'TX-1084', 'CASH_ON_DELIVERY', CURRENT_DATE, 'CANCELED', 23);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (409.8, 'TX-1085', 'MASTER_CARD', CURRENT_DATE, 'CANCELED', 20);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (919.54, 'TX-1086', 'CASH_ON_DELIVERY', CURRENT_DATE, 'DECLINED', 33);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (652.75, 'TX-1087', 'DISCOVER', CURRENT_DATE, 'CANCELED', 42);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (173.3, 'TX-1088', 'STRIPE', CURRENT_DATE, 'PENDING', 50);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (279.29, 'TX-1089', 'DISCOVER', CURRENT_DATE, 'PENDING', 5);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (955.18, 'TX-1090', 'MTN_MOBILE_MONEY', CURRENT_DATE, 'DECLINED', 7);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (484.87, 'TX-1091', 'STRIPE', CURRENT_DATE, 'PENDING', 38);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (871.89, 'TX-1092', 'PAYPAL', CURRENT_DATE, 'PENDING', 49);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (213.57, 'TX-1093', 'STRIPE', CURRENT_DATE, 'DECLINED', 44);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (689.21, 'TX-1094', 'STRIPE', CURRENT_DATE, 'DECLINED', 18);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (237.43, 'TX-1095', 'STRIPE', CURRENT_DATE, 'CANCELED', 28);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (831.76, 'TX-1096', 'DISCOVER', CURRENT_DATE, 'FAILED', 15);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (576.93, 'TX-1097', 'CASH_ON_DELIVERY', CURRENT_DATE, 'CANCELED', 29);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (505.1, 'TX-1098', 'AMERICAN_EXPRESS', CURRENT_DATE, 'FAILED', 21);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (865.19, 'TX-1099', 'AMERICAN_EXPRESS', CURRENT_DATE, 'DECLINED', 4);
INSERT INTO payments (amount, transaction_id, payment_method, payment_date, status, user_id) VALUES (971.39, 'TX-1100', 'DISCOVER', CURRENT_DATE, 'FAILED', 18);


-- BOOKINGS
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-07-21', '2025-07-25', 1054.72, 'CHECKED_IN', 'FAILED', CURRENT_TIMESTAMP, 31, 'BR-1001', 4, 1);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-01-11', '2025-01-17', 1078.87, 'CHECKED_IN', 'CANCELED', CURRENT_TIMESTAMP, 43, 'BR-1002', 6, 2);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-03-02', '2025-03-11', 1342.25, 'CHECKED_OUT', 'CONFIRMED', CURRENT_TIMESTAMP, 14, 'BR-1003', 3, 3);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-02-01', '2025-02-06', 1708.74, 'CANCELED', 'CONFIRMED', CURRENT_TIMESTAMP, 32, 'BR-1004', 3, 4);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-02-03', '2025-02-09', 518.23, 'CONFIRMED', 'DECLINED', CURRENT_TIMESTAMP, 30, 'BR-1005', 6, 5);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-05-03', '2025-05-07', 1444.95, 'CHECKED_IN', 'FAILED', CURRENT_TIMESTAMP, 50, 'BR-1006', 7, 6);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-08-14', '2025-08-23', 1621.2, 'PENDING', 'PENDING', CURRENT_TIMESTAMP, 27, 'BR-1007', 5, 7);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-09-18', '2025-09-23', 1345.76, 'CONFIRMED', 'FAILED', CURRENT_TIMESTAMP, 45, 'BR-1008', 4, 8);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-02-13', '2025-02-17', 102.16, 'PENDING', 'CONFIRMED', CURRENT_TIMESTAMP, 35, 'BR-1009', 1, 9);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-04-19', '2025-04-28', 1247.21, 'CONFIRMED', 'PENDING', CURRENT_TIMESTAMP, 24, 'BR-1010', 3, 10);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-04-20', '2025-04-22', 541.51, 'CHECKED_OUT', 'CONFIRMED', CURRENT_TIMESTAMP, 12, 'BR-1011', 4, 11);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-06-21', '2025-06-22', 124.23, 'CANCELED', 'CONFIRMED', CURRENT_TIMESTAMP, 16, 'BR-1012', 3, 12);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-03-14', '2025-03-18', 1575.45, 'CONFIRMED', 'CANCELED', CURRENT_TIMESTAMP, 43, 'BR-1013', 7, 13);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-05-21', '2025-05-26', 1603.57, 'PENDING', 'CONFIRMED', CURRENT_TIMESTAMP, 39, 'BR-1014', 1, 14);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-01-20', '2025-01-29', 1991.85, 'CANCELED', 'FAILED', CURRENT_TIMESTAMP, 18, 'BR-1015', 4, 15);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-08-04', '2025-08-12', 131.44, 'CONFIRMED', 'PENDING', CURRENT_TIMESTAMP, 43, 'BR-1016', 3, 16);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-01-03', '2025-01-11', 1108.19, 'PENDING', 'FAILED', CURRENT_TIMESTAMP, 32, 'BR-1017', 10, 17);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-12-08', '2025-12-15', 1014.84, 'PENDING', 'PENDING', CURRENT_TIMESTAMP, 23, 'BR-1018', 9, 18);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-04-10', '2025-04-15', 837.13, 'CONFIRMED', 'DECLINED', CURRENT_TIMESTAMP, 38, 'BR-1019', 10, 19);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-03-17', '2025-03-24', 921.73, 'CHECKED_IN', 'DECLINED', CURRENT_TIMESTAMP, 10, 'BR-1020', 4, 20);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-10-25', '2025-10-26', 691.98, 'CANCELED', 'CONFIRMED', CURRENT_TIMESTAMP, 48, 'BR-1021', 8, 21);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-02-17', '2025-02-27', 512.09, 'CANCELED', 'FAILED', CURRENT_TIMESTAMP, 34, 'BR-1022', 2, 22);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-07-20', '2025-07-29', 1240.02, 'CANCELED', 'CANCELED', CURRENT_TIMESTAMP, 6, 'BR-1023', 4, 23);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-06-09', '2025-06-17', 1152.95, 'PENDING', 'PENDING', CURRENT_TIMESTAMP, 4, 'BR-1024', 7, 24);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-02-09', '2025-02-19', 1964.17, 'PENDING', 'FAILED', CURRENT_TIMESTAMP, 41, 'BR-1025', 1, 25);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-06-11', '2025-06-14', 972.28, 'CANCELED', 'DECLINED', CURRENT_TIMESTAMP, 5, 'BR-1026', 9, 26);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-08-24', '2025-09-02', 919.77, 'CHECKED_OUT', 'CANCELED', CURRENT_TIMESTAMP, 40, 'BR-1027', 4, 27);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-12-01', '2025-12-09', 754.66, 'PENDING', 'PENDING', CURRENT_TIMESTAMP, 3, 'BR-1028', 6, 28);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-12-10', '2025-12-16', 1904.49, 'CONFIRMED', 'DECLINED', CURRENT_TIMESTAMP, 6, 'BR-1029', 4, 29);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-02-10', '2025-02-12', 314.31, 'PENDING', 'CANCELED', CURRENT_TIMESTAMP, 44, 'BR-1030', 5, 30);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-10-20', '2025-10-27', 1713.25, 'PENDING', 'DECLINED', CURRENT_TIMESTAMP, 46, 'BR-1031', 9, 31);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-06-17', '2025-06-27', 123.18, 'CHECKED_IN', 'CANCELED', CURRENT_TIMESTAMP, 18, 'BR-1032', 5, 32);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-10-16', '2025-10-20', 1500.4, 'CONFIRMED', 'DECLINED', CURRENT_TIMESTAMP, 19, 'BR-1033', 10, 33);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-06-03', '2025-06-10', 1848.04, 'CANCELED', 'CONFIRMED', CURRENT_TIMESTAMP, 29, 'BR-1034', 6, 34);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-10-13', '2025-10-19', 1285.45, 'CHECKED_OUT', 'FAILED', CURRENT_TIMESTAMP, 37, 'BR-1035', 10, 35);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-06-16', '2025-06-21', 1464.59, 'CHECKED_IN', 'CONFIRMED', CURRENT_TIMESTAMP, 9, 'BR-1036', 6, 36);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-06-16', '2025-06-21', 1561.4, 'CHECKED_IN', 'CANCELED', CURRENT_TIMESTAMP, 27, 'BR-1037', 6, 37);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-10-01', '2025-10-03', 1716.66, 'PENDING', 'CANCELED', CURRENT_TIMESTAMP, 18, 'BR-1038', 7, 38);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-12-23', '2026-01-02', 1461.07, 'PENDING', 'CONFIRMED', CURRENT_TIMESTAMP, 13, 'BR-1039', 2, 39);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-10-22', '2025-10-28', 999.12, 'CHECKED_IN', 'DECLINED', CURRENT_TIMESTAMP, 15, 'BR-1040', 8, 40);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-02-16', '2025-02-20', 823.26, 'PENDING', 'CONFIRMED', CURRENT_TIMESTAMP, 44, 'BR-1041', 9, 41);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-05-14', '2025-05-17', 694.98, 'CONFIRMED', 'CONFIRMED', CURRENT_TIMESTAMP, 48, 'BR-1042', 7, 42);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-10-22', '2025-10-26', 107.78, 'CHECKED_IN', 'CANCELED', CURRENT_TIMESTAMP, 23, 'BR-1043', 10, 43);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-03-06', '2025-03-13', 1756.39, 'CHECKED_OUT', 'FAILED', CURRENT_TIMESTAMP, 19, 'BR-1044', 4, 44);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-10-13', '2025-10-21', 353.61, 'CANCELED', 'CANCELED', CURRENT_TIMESTAMP, 12, 'BR-1045', 8, 45);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-03-13', '2025-03-14', 1395.97, 'CHECKED_IN', 'PENDING', CURRENT_TIMESTAMP, 47, 'BR-1046', 9, 46);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-07-01', '2025-07-07', 208.59, 'CANCELED', 'PENDING', CURRENT_TIMESTAMP, 50, 'BR-1047', 4, 47);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-02-06', '2025-02-11', 291.67, 'CHECKED_OUT', 'DECLINED', CURRENT_TIMESTAMP, 4, 'BR-1048', 6, 48);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-07-25', '2025-08-02', 132.48, 'CHECKED_IN', 'CANCELED', CURRENT_TIMESTAMP, 17, 'BR-1049', 2, 49);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-02-16', '2025-02-26', 1941.48, 'CHECKED_OUT', 'PENDING', CURRENT_TIMESTAMP, 49, 'BR-1050', 3, 50);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-12-25', '2025-12-29', 1804.86, 'PENDING', 'CANCELED', CURRENT_TIMESTAMP, 27, 'BR-1051', 6, 51);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-05-21', '2025-05-23', 1980.75, 'CONFIRMED', 'PENDING', CURRENT_TIMESTAMP, 6, 'BR-1052', 5, 52);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-03-15', '2025-03-20', 1940.04, 'PENDING', 'PENDING', CURRENT_TIMESTAMP, 6, 'BR-1053', 1, 53);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-09-23', '2025-10-03', 1660.55, 'CONFIRMED', 'CANCELED', CURRENT_TIMESTAMP, 27, 'BR-1054', 2, 54);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-03-01', '2025-03-03', 1554.56, 'CHECKED_OUT', 'PENDING', CURRENT_TIMESTAMP, 40, 'BR-1055', 2, 55);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-05-08', '2025-05-17', 882.83, 'CHECKED_IN', 'DECLINED', CURRENT_TIMESTAMP, 48, 'BR-1056', 4, 56);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-03-07', '2025-03-11', 298.33, 'CHECKED_IN', 'CANCELED', CURRENT_TIMESTAMP, 39, 'BR-1057', 1, 57);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-12-09', '2025-12-15', 354.41, 'CONFIRMED', 'CONFIRMED', CURRENT_TIMESTAMP, 19, 'BR-1058', 3, 58);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-01-10', '2025-01-16', 114.78, 'CHECKED_OUT', 'CANCELED', CURRENT_TIMESTAMP, 36, 'BR-1059', 2, 59);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-05-25', '2025-05-26', 1668.7, 'CHECKED_OUT', 'CONFIRMED', CURRENT_TIMESTAMP, 20, 'BR-1060', 10, 60);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-11-07', '2025-11-12', 1104.75, 'CHECKED_OUT', 'FAILED', CURRENT_TIMESTAMP, 44, 'BR-1061', 8, 61);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-12-04', '2025-12-10', 421.98, 'CONFIRMED', 'FAILED', CURRENT_TIMESTAMP, 24, 'BR-1062', 5, 62);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-12-21', '2025-12-25', 1265.21, 'CONFIRMED', 'FAILED', CURRENT_TIMESTAMP, 34, 'BR-1063', 6, 63);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-08-01', '2025-08-03', 187.03, 'CANCELED', 'PENDING', CURRENT_TIMESTAMP, 25, 'BR-1064', 5, 64);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-10-11', '2025-10-20', 1002.16, 'CANCELED', 'PENDING', CURRENT_TIMESTAMP, 1, 'BR-1065', 2, 65);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-03-05', '2025-03-13', 1039.81, 'CANCELED', 'CANCELED', CURRENT_TIMESTAMP, 35, 'BR-1066', 2, 66);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-01-22', '2025-01-27', 518.52, 'CHECKED_IN', 'FAILED', CURRENT_TIMESTAMP, 19, 'BR-1067', 8, 67);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-09-19', '2025-09-29', 1902.94, 'CANCELED', 'PENDING', CURRENT_TIMESTAMP, 13, 'BR-1068', 4, 68);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-05-11', '2025-05-21', 515.1, 'CHECKED_IN', 'CANCELED', CURRENT_TIMESTAMP, 33, 'BR-1069', 6, 69);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-08-20', '2025-08-24', 762.64, 'CANCELED', 'CANCELED', CURRENT_TIMESTAMP, 1, 'BR-1070', 6, 70);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-07-25', '2025-07-29', 1968.8, 'CHECKED_IN', 'DECLINED', CURRENT_TIMESTAMP, 44, 'BR-1071', 8, 71);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-12-06', '2025-12-10', 1877.24, 'CANCELED', 'CONFIRMED', CURRENT_TIMESTAMP, 2, 'BR-1072', 6, 72);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-01-09', '2025-01-12', 580.75, 'PENDING', 'CONFIRMED', CURRENT_TIMESTAMP, 7, 'BR-1073', 1, 73);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-11-23', '2025-12-03', 1641.54, 'CONFIRMED', 'DECLINED', CURRENT_TIMESTAMP, 23, 'BR-1074', 3, 74);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-09-01', '2025-09-09', 462.05, 'PENDING', 'FAILED', CURRENT_TIMESTAMP, 20, 'BR-1075', 4, 75);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-07-05', '2025-07-06', 1837.25, 'PENDING', 'CONFIRMED', CURRENT_TIMESTAMP, 24, 'BR-1076', 10, 76);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-01-12', '2025-01-20', 1013.7, 'CONFIRMED', 'PENDING', CURRENT_TIMESTAMP, 4, 'BR-1077', 5, 77);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-09-08', '2025-09-11', 1561.5, 'CONFIRMED', 'CANCELED', CURRENT_TIMESTAMP, 45, 'BR-1078', 9, 78);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-10-14', '2025-10-20', 330.54, 'CHECKED_IN', 'CONFIRMED', CURRENT_TIMESTAMP, 1, 'BR-1079', 4, 79);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-04-09', '2025-04-11', 855.72, 'PENDING', 'DECLINED', CURRENT_TIMESTAMP, 46, 'BR-1080', 7, 80);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-08-01', '2025-08-10', 1946.55, 'CANCELED', 'FAILED', CURRENT_TIMESTAMP, 9, 'BR-1081', 10, 81);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-05-16', '2025-05-22', 1637.03, 'PENDING', 'DECLINED', CURRENT_TIMESTAMP, 49, 'BR-1082', 9, 82);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-08-16', '2025-08-24', 1531.03, 'CONFIRMED', 'FAILED', CURRENT_TIMESTAMP, 13, 'BR-1083', 8, 83);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-06-08', '2025-06-15', 710.24, 'CONFIRMED', 'DECLINED', CURRENT_TIMESTAMP, 19, 'BR-1084', 6, 84);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-11-06', '2025-11-14', 1502.16, 'CHECKED_OUT', 'DECLINED', CURRENT_TIMESTAMP, 11, 'BR-1085', 5, 85);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-12-13', '2025-12-15', 330.88, 'CHECKED_OUT', 'CONFIRMED', CURRENT_TIMESTAMP, 24, 'BR-1086', 4, 86);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-02-25', '2025-03-01', 1213.99, 'CHECKED_OUT', 'FAILED', CURRENT_TIMESTAMP, 44, 'BR-1087', 2, 87);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-03-16', '2025-03-26', 1107.27, 'PENDING', 'CANCELED', CURRENT_TIMESTAMP, 12, 'BR-1088', 10, 88);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-01-21', '2025-01-26', 509.79, 'CANCELED', 'CONFIRMED', CURRENT_TIMESTAMP, 50, 'BR-1089', 9, 89);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-10-12', '2025-10-19', 1782.16, 'CHECKED_OUT', 'FAILED', CURRENT_TIMESTAMP, 21, 'BR-1090', 5, 90);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-03-03', '2025-03-09', 925.14, 'CHECKED_IN', 'CANCELED', CURRENT_TIMESTAMP, 32, 'BR-1091', 10, 91);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-01-05', '2025-01-10', 1281.75, 'CHECKED_OUT', 'DECLINED', CURRENT_TIMESTAMP, 27, 'BR-1092', 4, 92);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-06-07', '2025-06-13', 1356.58, 'CHECKED_IN', 'DECLINED', CURRENT_TIMESTAMP, 7, 'BR-1093', 4, 93);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-05-04', '2025-05-14', 841.93, 'CONFIRMED', 'CONFIRMED', CURRENT_TIMESTAMP, 40, 'BR-1094', 6, 94);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-08-05', '2025-08-07', 1511.46, 'CHECKED_OUT', 'DECLINED', CURRENT_TIMESTAMP, 35, 'BR-1095', 8, 95);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-03-11', '2025-03-16', 450.19, 'CHECKED_OUT', 'DECLINED', CURRENT_TIMESTAMP, 10, 'BR-1096', 3, 96);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-02-15', '2025-02-16', 990.11, 'CHECKED_IN', 'DECLINED', CURRENT_TIMESTAMP, 48, 'BR-1097', 1, 97);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-08-18', '2025-08-25', 1832.35, 'CANCELED', 'CANCELED', CURRENT_TIMESTAMP, 20, 'BR-1098', 8, 98);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-08-09', '2025-08-12', 1523.88, 'CHECKED_OUT', 'DECLINED', CURRENT_TIMESTAMP, 9, 'BR-1099', 9, 99);
INSERT INTO bookings (check_in_date, check_out_date, total_price, booking_status, payment_status, created_at, user_id, reference_code, room_id, payment_id) VALUES ('2025-12-20', '2025-12-28', 1214.41, 'CANCELED', 'DECLINED', CURRENT_TIMESTAMP, 1, 'BR-1100', 5, 100);

-- NOTIFICATIONS
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Fast strong provide.', 'michael96@smith.com', 'Against today hit owner take others onto. Trip wrong nor. Experience myself himself drop late.', CURRENT_TIMESTAMP, 'PUSH_NOTIFICATION', 43);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Financial brother including.', 'dlarsen@gmail.com', 'Attention place I simple lead company. Music soon resource point billion material several.', CURRENT_TIMESTAMP, 'WHATSAPP', 89);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Pattern more threat join.', 'qsullivan@stephenson.info', 'Skin crime itself change. Large few leg represent.', CURRENT_TIMESTAMP, 'PUSH_NOTIFICATION', 40);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Executive need.', 'imosley@jones.org', 'Success simply team. Reveal try fine yourself but along.', CURRENT_TIMESTAMP, 'EMAIL', 69);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('During water because.', 'pattersonjohn@po.biz', 'Maintain laugh art. Check nearly letter. Bring man project artist exactly yard believe.', CURRENT_TIMESTAMP, 'PUSH_NOTIFICATION', 37);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Style about.', 'naustin@hotmail.com', 'Including away five alone market phone local dog.', CURRENT_TIMESTAMP, 'PUSH_NOTIFICATION', 64);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Foot build father.', 'adam01@campbell.biz', 'Economic nation box international. Great region onto yourself.', CURRENT_TIMESTAMP, 'PUSH_NOTIFICATION', 23);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Poor.', 'christopher20@yahoo.com', 'Mr interview response turn firm lose affect.', CURRENT_TIMESTAMP, 'PUSH_NOTIFICATION', 1);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Him source live ground.', 'johnpitts@leonard.com', 'Author think wall low suffer only. Daughter better it personal dinner position.', CURRENT_TIMESTAMP, 'IN_APP_NOTIFICATION', 1);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Commercial role.', 'charles66@chase-byrd.net', 'Lawyer can today exist. Thank reveal figure organization how same hour. Size walk media news.', CURRENT_TIMESTAMP, 'PUSH_NOTIFICATION', 25);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Future carry director.', 'gina89@cardenas.biz', 'Maybe series suffer. Region baby quite yeah culture leader.', CURRENT_TIMESTAMP, 'WHATSAPP', 93);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Under whole hope.', 'jasonha@ka.net', 'Chance six wait because can sit certain. Candidate southern go eye beyond term.', CURRENT_TIMESTAMP, 'SMS', 76);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Bring.', 'quinnmark@rivera.net', 'Station all wonder couple sister leave more. Rate for easy listen. Company wide nor nor.', CURRENT_TIMESTAMP, 'PUSH_NOTIFICATION', 73);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Kid across sea environment.', 'haynesjessica@yahoo.com', 'Film itself for. Number example quite suggest argue.', CURRENT_TIMESTAMP, 'WHATSAPP', 28);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Interview feel glass.', 'stevenvalentine@holt.com', 'Mission role between boy property. Law I her. Positive yet carry sea measure can story produce.', CURRENT_TIMESTAMP, 'PUSH_NOTIFICATION', 53);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Action few.', 'kthompson@hotmail.com', 'Game arm bill every staff day always. Force street little anything.', CURRENT_TIMESTAMP, 'PUSH_NOTIFICATION', 46);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Upon.', 'otaylor@hotmail.com', 'Enough amount education focus. Option what open agreement chance series continue price.', CURRENT_TIMESTAMP, 'WHATSAPP', 46);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Choose adult defense.', 'bowenantonio@gmail.com', 'When age drop continue exactly. Choice with measure.', CURRENT_TIMESTAMP, 'SMS', 71);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Policy security professor.', 'josephmckay@hotmail.com', 'Room throw yes wish.
Style head describe yet simple reason. On movie draw source three include.', CURRENT_TIMESTAMP, 'WHATSAPP', 72);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Only each.', 'ibray@gmail.com', 'Require join message should where clear. Listen be term all.', CURRENT_TIMESTAMP, 'SMS', 55);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Lay matter first.', 'monroedavid@yahoo.com', 'Little reduce traditional north expert process smile. Political tough property exist theory.', CURRENT_TIMESTAMP, 'SMS', 40);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Hope gun.', 'mpena@lloyd-meyer.com', 'Chair even reach bag station. Worker similar reflect usually.', CURRENT_TIMESTAMP, 'SMS', 61);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Mention measure hard.', 'shannonsanders@avery.com', 'Old wait design. Prove former organization realize learn turn.', CURRENT_TIMESTAMP, 'EMAIL', 45);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Yes home chair.', 'adam75@yahoo.com', 'At if next population lose long identify. Career scene method opportunity.', CURRENT_TIMESTAMP, 'PUSH_NOTIFICATION', 12);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Will religious especially.', 'uhamilton@gmail.com', 'Dog community age production relate once each. Success begin experience one particularly.', CURRENT_TIMESTAMP, 'IN_APP_NOTIFICATION', 8);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Plan billion reach.', 'margaret84@yahoo.com', 'Condition tend rock cell. Parent someone seek city go wall. Instead every laugh later fly.', CURRENT_TIMESTAMP, 'PUSH_NOTIFICATION', 86);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Finally particularly professor mind.', 'adam79@castillo-york.net', 'Discover similar respond tell campaign determine. Democratic number center better next right.', CURRENT_TIMESTAMP, 'WHATSAPP', 22);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Well trip government run.', 'richard@hotmail.com', 'Wind western cell either.', CURRENT_TIMESTAMP, 'WHATSAPP', 20);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Owner talk show.', 'john02@smith.com', 'Book determine issue during. Sign eat look recently office. Movement question hear woman determine.', CURRENT_TIMESTAMP, 'PUSH_NOTIFICATION', 80);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Cell office century.', 'uandrews@henry.com', 'Recent age treatment truth market meet bad.', CURRENT_TIMESTAMP, 'IN_APP_NOTIFICATION', 95);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('On budget allow.', 'phillipcrawford@gmail.com', 'Sure make art expert. Stuff lose quickly wife.', CURRENT_TIMESTAMP, 'PUSH_NOTIFICATION', 2);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Professional civil effort.', 'tannergarrett@davis.com', 'Heart Democrat popular huge stock for thus wait. Miss model task card.', CURRENT_TIMESTAMP, 'IN_APP_NOTIFICATION', 86);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Use break generation.', 'janetphillips@burns.com', 'College simply north if skin. Likely administration from build a town.', CURRENT_TIMESTAMP, 'IN_APP_NOTIFICATION', 31);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Once pattern entire.', 'danielhernandez@webb.com', 'Test party blood reason her car. Science technology road mind power sound they.
Around central me.', CURRENT_TIMESTAMP, 'WHATSAPP', 56);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Idea issue size.', 'cartergabriel@johnson.com', 'Apply can hot gas want network. Them skin popular actually. Role within follow two.', CURRENT_TIMESTAMP, 'IN_APP_NOTIFICATION', 31);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Audience act air person.', 'tsmith@glass-stokes.com', 'Just sure including somebody level need. Break paper authority look anyone impact big.', CURRENT_TIMESTAMP, 'PUSH_NOTIFICATION', 88);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Customer window thing.', 'melissa22@yahoo.com', 'Color argue board window media minute brother. Be quality artist material.', CURRENT_TIMESTAMP, 'PUSH_NOTIFICATION', 42);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Kid onto should.', 'adunn@gmail.com', 'Among choice compare this. Finally leader expect forward.', CURRENT_TIMESTAMP, 'IN_APP_NOTIFICATION', 43);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Vote.', 'hornebrian@yahoo.com', 'Range important meeting. History suffer girl hit realize. Travel source step own price real only.', CURRENT_TIMESTAMP, 'SMS', 9);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Through old.', 'freydonald@gmail.com', 'Energy at wish poor than far outside. By lead sometimes travel.
Matter society raise. For job back.', CURRENT_TIMESTAMP, 'SMS', 13);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Something call.', 'erika43@gmail.com', 'Tv he maintain rise. Deep half center. Health not owner house man such clear financial.', CURRENT_TIMESTAMP, 'EMAIL', 43);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Where.', 'scotteric@graham.com', 'Senior man according side sort. President audience war.', CURRENT_TIMESTAMP, 'IN_APP_NOTIFICATION', 61);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Worry material.', 'mgamble@hotmail.com', 'Talk focus before close loss glass.', CURRENT_TIMESTAMP, 'SMS', 77);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Society attorney example.', 'robert94@ramsey-james.biz', 'Arm for ask marriage hot town.', CURRENT_TIMESTAMP, 'IN_APP_NOTIFICATION', 87);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Prove make explain shoulder.', 'lmyers@long-jacobson.net', 'Whole order western. Recent however end soldier present. Important great only available walk walk.', CURRENT_TIMESTAMP, 'PUSH_NOTIFICATION', 22);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Think a method.', 'amber30@soto.com', 'There piece audience various her. How officer line weight method. Exist gas visit.', CURRENT_TIMESTAMP, 'SMS', 5);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Course wall budget.', 'fishermichael@gmail.com', 'Cover fish explain meeting continue choice local. Heavy can discuss edge.', CURRENT_TIMESTAMP, 'PUSH_NOTIFICATION', 56);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('South lead middle.', 'caleb15@cummings-cook.com', 'Own unit state president traditional certainly treatment.', CURRENT_TIMESTAMP, 'PUSH_NOTIFICATION', 57);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Task model dream.', 'markkeller@msoto.com', 'Tell professor represent of career identify whose. Own reveal guy she cover do involve.', CURRENT_TIMESTAMP, 'IN_APP_NOTIFICATION', 81);
INSERT INTO notifications (subject, recipient_email, body, created_at, notification_type, booking_id) VALUES ('Million listen then.', 'valeealex@obrien.info', 'Marriage suddenly outside him customer many spring. College hand black art energy campaign both.', CURRENT_TIMESTAMP, 'EMAIL', 86);