apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hotel-frontend-hpa
  namespace: hotel-booking-system
  labels:
    app.kubernetes.io/name: hotel-booking
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: hotel-booking-ui
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hotel-frontend
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
