apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-frontend
  namespace: hotel-booking-system
  labels:
    app.kubernetes.io/name: hotel-booking
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: hotel-booking-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: hotel-booking-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hotel-booking
        app.kubernetes.io/component: frontend
        app.kubernetes.io/instance: hotel-booking-ui
    spec:
      containers:
        - name: hotel-frontend
          image: dunky2012/cs489-hotel-frontend:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-frontend-svc
  namespace: hotel-booking-system
  labels:
    app.kubernetes.io/name: hotel-booking
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: hotel-booking-ui
spec:
  selector:
    app.kubernetes.io/instance: hotel-booking-ui
  ports:
    - port: 3000 # External port browser will use
      targetPort: 3000 # NGINX container listens on 3000
  type: ClusterIP
