apiVersion: v1
kind: Service
metadata:
  name: hotel-booking-backend-svc
  namespace: hotel-booking-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: hotel-booking-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
