apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hotel-booking-system-hpa
  namespace: hotel-booking-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hotel-booking-backend
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50