
name: Java CLI CI (Lab1b only)

on:
  push:
    paths:
      - 'assignment-lab1b/Lab1b-Employee-PensionPlan/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'assignment-lab1b/Lab1b-Employee-PensionPlan/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: assignment-lab1b/Lab1b-Employee-PensionPlan

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean install

    - name: (Optional) Run tests
      run: mvn test

