apiVersion: v1
kind: Service
metadata:
  name: hotel-booking-backend-svc
  namespace: {{ .Values.microservice.namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{.Values.microservice.name}}
  ports:
    - port: {{.Values.workload.port}}
      targetPort: {{.Values.workload.port}}

