apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.microservice.name}}-config
  namespace: {{ .Values.microservice.namespace }}
data:
  SPRING_R2DBC_URL: {{ .Values.env.SPRING_R2DBC_URL | quote }}
