apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-ip-pool
  namespace: metallb-system
spec:
  addresses:
    - 107.175.82.41/32  # your public IP

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public-l2
  namespace: metallb-system
