apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: hotel-booking-system
spec:
  clusterIP: None  # Headless Service for StatefulSet
  selector:
    app.kubernetes.io/instance: postgres-db
  ports:
    - port: 5432
      targetPort: 5432
